// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS4bKwz7QEqOQ5ntZkC8uzK934mmNuPzw',
    appId: '1:1081470959670:web:890ae53598914bd8205897',
    messagingSenderId: '1081470959670',
    projectId: 'college-connect-gmrit',
    authDomain: 'college-connect-gmrit.firebaseapp.com',
    storageBucket: 'college-connect-gmrit.firebasestorage.app',
    measurementId: 'G-H70DHGVPPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbOv-kSv35a_fhdY0AIR4TKSVv7RftIAE',
    appId: '1:1081470959670:android:3d37173a83eb54d5205897',
    messagingSenderId: '1081470959670',
    projectId: 'college-connect-gmrit',
    storageBucket: 'college-connect-gmrit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFSKanhbCqlfWGG7i81C12dg7MzA9creA',
    appId: '1:1081470959670:ios:5d41a0c25f2e9dca205897',
    messagingSenderId: '1081470959670',
    projectId: 'college-connect-gmrit',
    storageBucket: 'college-connect-gmrit.firebasestorage.app',
    iosBundleId: 'com.example.collegeConnectd',
  );
}
